trigger:
- main  # Replace 'main' with the appropriate branch trigger

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Cleanup
  jobs:
  - job: CleanupResources
    steps:
    
    - task: CloudFormationDeleteStack@1
      inputs:
        awsCredentials: $(service-connection)
        regionName: $(name)
        stackName: $(stackName)
        logRequest: true
        logResponse: true